namespace: wallboard

vnc:
  enabled: true

daemonset:
  name: wallboard
  labels:
    name: test-wallboard
  url: https://google.com
  images:
    x11: registry.opensuse.org/home/atgracey/wallboardos/15.5/x11:notaskbar
    audio: registry.opensuse.org/home/atgracey/wallboardos/15.5/pa:latest
    wallboard: docker.io/atgracey/kiosk-test:latest
    vnc: registry.opensuse.org/home/atgracey/wallboardos/15.5/vnc:vnc
  imagePullPolicy: Always
  runAsUser: 1000
  optionalVolume:
    enabled: false
    hostPath: ""
    mountPath: /usr/share/wallpapers/openSUSEdefault/contents/images/1920x1080.jpg
