apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonset.labels.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.daemonset.labels.name }}
    spec:
      initContainers:
        - name: x11
          image: {{ .Values.daemonset.images.x11 }}
          imagePullPolicy: {{ .Values.daemonset.imagePullPolicy }}
          restartPolicy: Always
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /tmp/.X11-unix/
              name: xsocket
            - mountPath: /home/user/xauthority/
              name: xauthority
            - mountPath: /run/udev/data/
              name: udev-data
          {{- if .Values.daemonset.optionalVolume.enabled }}
            - mountPath: {{ .Values.daemonset.optionalVolume.mountPath }}
              name: optional-volume
              readOnly: true
          {{- end }}
        - name: audio
          image: {{ .Values.daemonset.images.audio }}
          command: ["bash"]
          args: ["-c", "chmod a+rw /dev/snd/*; pulseaudio"]
          imagePullPolicy: {{ .Values.daemonset.imagePullPolicy }}
          restartPolicy: Always
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          env:
            - name: PULSE_SERVER
              value: "127.0.0.1"
            - name: DISPLAY
              value: ':0'
            - name: XAUTHORITY
              value: /root/xauthority/.xauth
          volumeMounts:
            - mountPath: /tmp/.X11-unix/
              name: xsocket
            - mountPath: /root/xauthority/
              name: xauthority
            - mountPath: /run/udev/data/
              name: udev-data
      containers:
        {{- if .Values.vnc.enabled }}
        - name: vnc
          command: ["x11vnc"]
          ports:
            - containerPort: 5900
              name: vnc
          env:
            - name: DISPLAY
              value: ':0'
            - name: XAUTHORITY
              value: /home/user/xauthority/.xauth
          image: {{ .Values.daemonset.images.vnc }}
          imagePullPolicy: {{ .Values.daemonset.imagePullPolicy }}
          volumeMounts:
            - mountPath: /tmp/.X11-unix/
              name: xsocket
            - mountPath: /home/user/xauthority/
              name: xauthority
        {{- end }}
        - name: wallboard
          env:
            - name: PULSE_SERVER
              value: '127.0.0.1'
            - name: DISPLAY
              value: ':0'
            - name: XAUTHORITY
              value: /home/user/xauthority/.xauth
          image: {{ .Values.daemonset.images.wallboard }}
          imagePullPolicy: {{ .Values.daemonset.imagePullPolicy }}
          securityContext:
            runAsUser: {{ .Values.daemonset.runAsUser }}
          volumeMounts:
            - mountPath: /tmp/.X11-unix/
              name: xsocket
            - mountPath: /home/user/xauthority/
              name: xauthority
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 5
      volumes:
        - name: xauthority
          emptyDir: {}
        - name: xsocket
          emptyDir: {}
        - name: udev-data
          hostPath:
            path: /run/udev/data/
            type: Directory
        {{- if .Values.daemonset.optionalVolume.enabled }}
        - name: optional-volume
          hostPath:
            path: {{ .Values.daemonset.optionalVolume.hostPath }}
            type: File
        {{- end }}
